### ISSUE TITLE
Images to CSV

### ISSUE THREAD

**Issue by avinashkoshal** [Kawcher123/Rice-Leaf-Disease-Detection-using-Machine-learning#1]
Hello,
I want to know how you have converted images to CSV.
On what basis you have extracted features and put them into csv

**Comment by Kawcher123** [comment]
I used an image filtering method (ColorLayoutFilter) in WEKA to convert images into features which  added 35 features in a arff file. Then I manually converted the arff file into csv .  https://m.youtube.com/watch?v=XBSJOkuAtCw

**Comment by avinashkoshal** [comment]
Thanks for such a quick response ...
It's really helpful. I am closing this issue now :)
